### PR TITLE
fix: Add map props in SpotLight.d.ts

### PR DESCRIPTION
**Pull request by Suprhimp**
### Why

https://github.com/mrdoob/three.js/issues/24993#issue-1457275589

### What

Since SpotLight can have map props, we have to add `map` property in SpotLight.d.ts

### Checklist

-   [ x ] Checked the target branch (current goes `master`, next goes `dev`)
-   [ x ] Added myself to contributors table
-   [ x ] Ready to be merged

### CODE REVIEW

**Comment by CodyJasonBennett** [comment]
Related three.js PR: https://github.com/mrdoob/three.js/pull/21944, https://threejs.org/examples/#webgl_lights_spotlight.

**Review by joshuaellis — APPROVED** [review]

**Comment by Suprhimp** [comment]
oops should I resolve conflict in my side?

**Comment by joshuaellis** [comment]
please.

**Comment by Suprhimp** [comment]
I closed PR for resolve conflict :)

**Pull request closed without merging**
