### PR TITLE
feat: adds CapsuleGeometry definitions

### PR DESCRIPTION
**Pull request by gsimone**
### Checklist

-   [x] Checked the target branch (current goes `master`, next goes `dev`)
-   [ ] Added myself to contributors table
-   [x] Ready to be merged

### CODE REVIEW

**Review by joshuaellis — APPROVED** [review]
⭐

**Comment by gsimone** [comment]
Gotta add it to the import 👍

**Comment by 0b5vr** [comment]
https://github.com/mrdoob/three.js/pull/23586

**Comment by joshuaellis** [comment]
@all-contributors add @gsimone for code

**Pull request merged**
