### PR TITLE
[InstancedMesh] geometry and material are optional

### LINKED ISSUE #92: InstancedMesh geometry & material are not optional
-   `three` version: `0.129.0`
-   `node` version: `16`
-   `npm` (or `yarn`) version: `7`

### Problem description:

geometry and material are not optional see https://github.com/pmndrs/racing-game/pull/128

### Relevant code:

```ts
    <instancedMesh ref={ref} args={[null, null, count]}>
      <boxGeometry args={[size, size, size]} />
      <meshBasicMaterial color="#5ecfff" transparent opacity={opacity} depthWrite={true} />
    </instancedMesh>
```

### Suggested solution:

geometry & material should be optional.

### PR DESCRIPTION
**Pull request by bjornstar**
### Why

The geometry and material arguments for the InstancedMesh constructor are optional. Fixes #92 

### What

Instead of using `?` we can declare them as `undefined`

### Checklist

-   [x] Added myself to contributors table
-   [x] Ready to be merged

### CODE REVIEW

**Review by joshuaellis — CHANGES_REQUESTED** [review]
Can you please make a test to example this behaviour?

**Comment by bjornstar** [comment]
> Can you please make a test to example this behaviour?

Sure, I have added a very basic test.

**Review by joshuaellis — DISMISSED** [review]
Thanks for the contribution! ⭐

**Comment by joshuaellis** [comment]
CI is failing, see errors (let me know if you cant)

**Comment by bjornstar** [comment]
> CI is failing, see errors (let me know if you cant)

It might be fixed, CI isn't running so I don't know.

**Pull request merged**
