### PR TITLE
README: Small improvements

### PR DESCRIPTION
**Pull request by satelllte**
Just a bit of small improvements for the README file. See each commit for the details

### CODE REVIEW

**Comment by Methuselah96** [comment]
I'm not sure about capitalizing three.js. It seems to be inconsistently capitalized in the main repo, but I see it more often in lower-case than upper-case.

**Comment by satelllte** [comment]
> lower-case than upper-case.

I think it's always capitalized (see official website titles, wiki, mdn links, etc.)

www.google.com/search?q=three.js

**Comment by Methuselah96** [comment]
Examples of lower-case:

image
image
image
image
image

It seems like it's often in lower-case when used in a sentence, which is the main usages in our README

**Comment by satelllte** [comment]
@Methuselah96 OK, reverted it.

**Review by Methuselah96 — APPROVED** [review]
Thanks!

**Pull request merged**
