### PR TITLE
Make dispose() available in SelectionHelper

### PR DESCRIPTION
**Pull request by autonomobil**
### Why
[#25090](https://github.com/mrdoob/three.js/issues/25090)

### What
include `dispose()` method in SelectionHelper TS declaration file

### Checklist

-   [x] Checked the target branch (current goes `master`, next goes `dev`)
-   [x] Added myself to contributors table (where can I find this?)
-   [x] Ready to be merged

### CODE REVIEW

**Comment by autonomobil** [comment]
What do I need to do to get this simple fix merged?

**Review by Methuselah96 — APPROVED** [review]
Looks good, thanks!

**Comment by Methuselah96** [comment]
Should be released whenever we release the next version.

**Comment by autonomobil** [comment]
Ok thanks, can you roughly estimate when this will be the case? This year, January, etc? :)

**Comment by Methuselah96** [comment]
Typically it happens once a month with a release that matches each release of three.js. There's still work being done on [r147](https://github.com/three-types/three-ts-types/issues/276), so whenever that is completed.

**Pull request merged**
