### PR TITLE
fix: Add missing fields to CCDIKSolver IKS

### PR DESCRIPTION
**Pull request by Trinovantes**
### Why

`minAngle` field is missing in IKS definition

`limitation` `rotationMin` `rotationMax` fields are missing in IKS.links definition

https://github.com/mrdoob/three.js/blob/master/examples/jsm/animation/CCDIKSolver.js#L39-L46

### What

Added missing fields

### Checklist

-   [x] Checked the target branch (current goes `master`, next goes `dev`)
-   [x] Added myself to contributors table
-   [x] Ready to be merged

### CODE REVIEW

**Review by noname0310 — COMMENTED** [review]
https://github.com/noname0310/web-mmd-viewer/blob/9d0a7bf3f84f7703f09ae470698f98888abc5d0f/src/asset/script/mmd/loader/MMDLoaderOverride.ts#L60

Based on the IK data generated by the mmd loader of three js, this is an wrong type.

The above code is a rewritten part of the mmd loader in typescript, and I checked that the type of IK Solver was wrong during the rewriting. Please refer to it

**Comment by Trinovantes** [comment]
I'm just following what the current implementation is expecting:

`minAngle`: https://github.com/mrdoob/three.js/blob/master/examples/jsm/animation/CCDIKSolver.js#L154

`limitation rotationMin rotationMax`: https://github.com/mrdoob/three.js/blob/master/examples/jsm/animation/CCDIKSolver.js#L118-L120

**Comment by noname0310** [comment]
The IKS interface type must be an array.

see https://github.com/mrdoob/three.js/blob/f021ec0c9051eb11d110b0c2b93305bffd0942e0/examples/jsm/animation/CCDIKSolver.js#L73

**Comment by noname0310** [comment]
I'm sorry, I was mistaken. I think your modification is right.

**Comment by joshuaellis** [comment]
Can you resolve the conflict errors please? also you should have automatically been added to the README table, did you use the command to add yourself?

**Comment by Trinovantes** [comment]
Sorry, I made the original changes on github's web ui

I've updated it with the command now

**Review by joshuaellis — APPROVED** [review]

**Comment by joshuaellis** [comment]
Thanks!

**Pull request merged**
