### PR TITLE
TSL: Fix label() usage in uniform()

### PR DESCRIPTION
**Pull request by Methuselah96**
https://github.com/mrdoob/three.js/pull/28548

### CODE REVIEW

**Comment by 0b5vr** [comment]
@Methuselah96 What is the intention of the commit https://github.com/three-types/three-ts-types/pull/1023/commits/4819e9c424a0421426e77d07575ccd81d174df3c ?
I assume that there was some inconvenience in term of maintainability?

I'm using methods on nodes of NodeMaterials (`NodeMaterial.positionNode.add()` for example). This commit made us unable to use node methods.

**Comment by Methuselah96** [comment]
@0b5vr The issue is that currently Typescript does not allow a `ShaderNodeObject<SubTypeNode>` to be assigned to `ShaderNodeObject<Node>` because of methods that return `this` like `UniformNode.label()`. I'm not sure what the best solution is. I've created https://github.com/three-types/three-ts-types/pull/1123 to track this issue. You can see that the `text-examples` build is failing (`test` is failing for unrelated reasons).

**Comment by 0b5vr** [comment]
> @0b5vr The issue is that currently Typescript does not allow a `ShaderNodeObject<SubTypeNode>` to be assigned to `ShaderNodeObject<Node>` because of methods that return `this` like `UniformNode.label()`.

Thank you for the explanation. hm...

**Comment by Methuselah96** [comment]
@0b5vr This should be fixed by https://github.com/three-types/three-ts-types/pull/1839 by getting rid of the `ShaderNodeObject` type altogether

**Comment by 0b5vr** [comment]
thank you!

**Pull request merged**
