### PR TITLE
feat: Generate constructor interfaces

### PR DESCRIPTION
**Pull request by capnmidnight**
### Why

In TypeScript, the parameters to a constructor can be retrieved with a utility type called `ConstructorParameters<Type>`: https://www.typescriptlang.org/docs/handbook/utility-types.html#constructorparameterstype

The Type parameter to ConstructorParameters expects a Constructor interface type, which is an interface with a `new` member and a `prototype` member.

By defining these *Constructor interfaces, Three.js class types can now be used with ConstructorParameters.

### What

I wrote a C# program to scan all the .d.ts files for class exports, extract an interface definition for the constructors, and insert the constructor interfaces after each class definition. My program correctly handles generic classes, multiple class definitions per file, and multiple constructor overloads. You can see that program here: https://github.com/capnmidnight/Juniper/blob/master/etc/GenerateConstructorTypes/Program.cs

### Checklist

-   [x] Checked the target branch (current goes `master`, next goes `dev`)
-   [x] Added myself to contributors table
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by joshuaellis** [comment]
I'm not sure I understand why we should do this? Also

/cc @Methuselah96 for your opinion

**Comment by capnmidnight** [comment]
Well, it lets you create functions and other classes that match the signature of the target class. Maybe one would do something like:

```typescript
const cache = new WeakMap<String, THREE.SphereGeometry>();

function createSphere(...params: ConstructorParameters<THREE.SphereGeometryConstructor>): THREE.SphereGeometry {
    const key = JSON.stringify(params);
    if (cache.has(key)) {
        return cache.get(key);
    }

    const value = new THREE.SphereGeometry(...params);
    cache.set(key, value);
    return value;
}

const a = createSphere(1, 10, 5);
const b = createSphere(1, 10, 5);

assertTrue(a === b);
```

You could also do something like:
```typescript
function vector(...params: ConstructorParameters<THREE.Vector3Constructor>): THREE.Vector3;
function vector(...params: ConstructorParameters<THREE.Vector4Constructor>): THREE.Vector4;
function vector(...params: ConstructorParameters<THREE.Vector3Constructor> | ConstructorParameters<THREE.Vector4Constructor>): THREE.Vector3 | THREE.Vector4 {
    if (params.length === 3) {
        return new THREE.Vector3(...params);
    }
    else {
        return new THREE.Vector4(...params);
    }
}

const v3 = vector(1, 2, 3);
const v4 = vector(1, 2, 3, 4);

assertTrue(v3 instanceof THREE.Vector3);
assertTrue(v4 instanceof THREE.Vector4);
```

**Comment by Methuselah96** [comment]
Could you do:
```ts
ConstructorParameters<typeof THREE.SphereGeometry>
```

Instead of:
```ts
ConstructorParameters<THREE.SphereGeometryConstructor>
```

**Comment by capnmidnight** [comment]
Ah, I had forgotten about `typeof X`.

The constructor interface does have the additional benefit of allowing one to pass constructors as parameters and still be able to call them with `new` and construct objects with them. Maybe that isn't that important of an issue, as there are few classes in Three.js that have the same constructor signature, and of the ones that due, they are very simple.

**Comment by Methuselah96** [comment]
Yeah, I don't think there's a common enough use-case to justify adding this amount of duplication at this point.

**Pull request closed without merging**
