### PR TITLE
examples/WebGL checks moved to examples/capabilities/WebGL

### PR DESCRIPTION
**Pull request by schwyzl**
The webgl capabilities example has moved to examples/capabilities

-   [x] Checked the target branch (current goes `master`, next goes `dev`)
-   [x] Added myself to contributors table
-   [x] Ready to be merged

### CODE REVIEW

**Comment by schwyzl** [comment]
This doesn't work for me, i get the following error:
`Property 'isWebGL2Available' does not exist on type 'typeof import("...@types/three/examples/jsm/capabilities/WebGL")'`

The export type was changed to 'default' in three, and I don't think I have converted this right to ts.

Any ideas?

**Comment by joshuaellis** [comment]
Have you got a link to the source for this? Easier for me to understand whats going on that way.

**Comment by schwyzl** [comment]
https://github.com/mrdoob/three.js/commit/ab21bee59055fe1003f0c2d3e2eecb4cbed4a8c4

**Comment by schwyzl** [comment]
The above link is the change to default export type and this is the current source file: https://github.com/mrdoob/three.js/blob/87ab8857957750e5a61dbf0a24b4e8e189efc63f/examples/jsm/capabilities/WebGL.js

**Comment by Michsior14** [comment]
This is a duplicate of #168

**Comment by joshuaellis** [comment]
closing in favour of #168

**Pull request closed without merging**
