### PR TITLE
fix: correctly import webxr types

### PR DESCRIPTION
**Pull request by Methuselah96**
Resolves https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60551#issuecomment-1139372590.

### CODE REVIEW

**Comment by CodyJasonBennett** [comment]
Would this have to be mirrored in other classes that make references to WebXR types like [WebXRController](https://github.com/three-types/three-ts-types/blob/master/types/three/src/renderers/webxr/WebXRController.d.ts)?

What would this look like for user-facing code?

**Comment by Methuselah96** [comment]
No, you only have to reference it in one file and then it's globally available. Users won't have to do anything different as far as I'm aware.

**Comment by CodyJasonBennett** [comment]
Seems this was quite the breaking change since projects using types <141 were importing from three, and in order to support ambient types with 141 they'd require a major bump to hike the peer dep, or also include `@types/webxr` likewise.

Any chance we can revert or export `@types/webxr` in a patch release?

**Comment by joshuaellis** [comment]
Sorry, I'm not sure what the problem you're trying to say is.

It sounds like to me people are installing the latest version of these types with the non equivalent version of three e.g r139, if this is the case this is an incorrect usage of the library.

Let me know if I've misunderstood?

**Comment by CodyJasonBennett** [comment]
`@types/three` no longer exports WebXR types since r141. This is a breaking change.

**Comment by joshuaellis** [comment]
Right, yeah if you can open a new issue for this, we can track it better there.

**Pull request merged**
