### PR TITLE
refactor: Create single utility type to encapsulate color argument

### LINKED ISSUE #29: Create single utility type to encapsulate color argument
### Describe the feature you'd like:

Certain functions & properties have the type `Color | string | number` because they create a `THREE.Color` in the function and those are the arguments that `THREE.Color` can take, like the example below:

```ts
    renderPass: (
        renderer: WebGLRenderer,
        passMaterial: Material,
        renderTarget: WebGLRenderTarget,
        clearColor: Color | string | number,
        clearAlpha: Color | string | number,
    ) => void;
```

### Suggested implementation:

Therefore we want to create a utility type so instead of typing `Color | string | number` we only need to write one, this would then need to replace all instances of the previous type across the codebase.

### PR DESCRIPTION
**Pull request by shuta13**
### What

Fix: https://github.com/three-types/three-ts-types/issues/29

### Checklist

-   [x] Added myself to contributors table
-   [ ] Ready to be merged

### CODE REVIEW

**Review by joshuaellis — APPROVED** [review]
This looks good to me @Methuselah96 it would be good to get your opinion too 👍🏼

**Review by Methuselah96 — APPROVED** [review]
Looks good to me. `CapsulatedColor` probably isn't my preferred term because "capsulated" makes me think there's a value "capsulated" inside an object instead of a union, but I can't think of any obviously better names at the moment.

**Comment by joshuaellis** [comment]
`UnitedColor`? or `UColor`?

**Comment by Methuselah96** [comment]
Yeah, either of those work for me. Maybe `ColorRepresentation` (although that's a bit longer)?

**Comment by joshuaellis** [comment]
I prefer `ColorRepresentation` @shuta13 would you mind making that change please? 🙏🏼

**Comment by shuta13** [comment]
@Methuselah96 @joshuaellis 

OK, changed. Please check out! : https://github.com/three-types/three-ts-types/pull/107/commits/7aca3fbf31c8a2759dd5a4dd0fd2437682dc0de9

**Review by Methuselah96 — APPROVED** [review]
🎉

**Review by joshuaellis — APPROVED** [review]

**Pull request merged**
