### PR TITLE
fix: adjust webgl example location and types

### PR DESCRIPTION
**Pull request by Michsior14**
### Why

`WebGL` example has changed the placement in the r137. https://github.com/mrdoob/three.js/blob/master/examples/jsm/capabilities/WebGL.js

### What

Move the file to the proper path and fix the export according to the code.

### Checklist

-   [x] Checked the target branch (current goes `master`, next goes `dev`)
-   [x] Added myself to contributors table
-   [x] Ready to be merged

### CODE REVIEW

**Comment by Michsior14** [comment]
@joshuaellis, @Methuselah96  Could you please review?

**Comment by joshuaellis** [comment]
Hey @Michsior14, I'll take a look this week. Thank you for the reminder ☺️

**Comment by Michsior14** [comment]
@joshuaellis bump ;)

**Review by joshuaellis — APPROVED** [review]

**Comment by joshuaellis** [comment]
Thanks!

**Pull request merged**
