### PR TITLE
Update IFCLoader declaration file

### PR DESCRIPTION
**Pull request by agviegas**
### Why

The IFCLoader has changed, and this is an update of their types and documentation.

### What / Checklist

- [x] Update a declaration file and add documentation.

### CODE REVIEW

**Comment by joshuaellis** [comment]
Hey @agviegas, thanks for the contribution, did you run `prettier:write` before submitting the PR? If you do that it'll correctly format the code for us and then the larger CI will run and we can go from there ⭐

**Review by joshuaellis — APPROVED** [review]

**Comment by joshuaellis** [comment]
Thanks for the contribution ⭐

**Comment by agviegas** [comment]
Hey, sorry! We were making some changes to the API and we're going to update this PR after that. We'll open a new PR. Thanks for the help! 😊

**Comment by joshuaellis** [comment]
No worries @agviegas, this won't be going live till r130 anyway, thanks for letting me know though.

**Pull request merged**
