### PR TITLE
feat (Nodes): more `tslFn` related typings

### PR DESCRIPTION
**Pull request by 0b5vr**
- Support `tslFn` with array arguments.
  - If the argument is an array, the array will be destructed.
- Support proxied `tslFn` arguments using `ProxiedTuple` / `ProxiedObject` .
- Updated rest of `tslFn` functions.
  - [V_GGX_SmithCorrelated.js](https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/functions/BSDF/V_GGX_SmithCorrelated.js)
  - [getGeometryRoughness.js](https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/functions/material/getGeometryRoughness.js)
  - [getRoughness.js](https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/functions/material/getRoughness.js)
  - [LightUtils](https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/lighting/LightUtils.js)
- Update and add MaterialX nodes.
  - Fix type of [mx_hsv.js](https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/materialx/lib/mx_hsv.js), [mx_noise.js](https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/materialx/lib/mx_noise.js), [MaterialXNodes.js](https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/materialx/MaterialXNodes.js)
  - Add missing methods of mx_noise.js
  - Add [mx_transform_color.js](https://github.com/mrdoob/three.js/blob/r160/examples/jsm/nodes/materialx/lib/mx_transform_color.js) typings
  - Update test cases, the directory name was `materials` instead of `materialx`, fixed this

I used [The TSL editor](https://threejs.org/examples/?q=tsl#webgpu_tsl_editor) to confirm whether the type matches the actual behavior.

### CODE REVIEW

**Comment by 0b5vr** [comment]
The test says:

```
1> /home/runner/work/three-ts-types/three-ts-types/DefinitelyTyped/types/three/test/unit/examples/jsm/nodes/ShaderNode/ShaderNode.ts

1>   75:23  error  TypeScript@4.6, 4.7, 4.8, 4.9, 5.0 compile error: 
1> Type of property 'cache' circularly references itself in mapped type '{ [Key in keyof NodeElements]: NodeElements[Key] extends (node: CacheNode, ...args: infer Args) => infer R ? (...args: Args) => R : never; }'      @definitelytyped/expect
1>   75:23  error  TypeScript@4.6, 4.7, 4.8, 4.9, 5.0 compile error: 
1> Type of property 'context' circularly references itself in mapped type '{ [Key in keyof NodeElements]: NodeElements[Key] extends (node: ContextNode, ...args: infer Args) => infer R ? (...args: Args) => R : never; }'  @definitelytyped/expect
```

I have no idea what to do...

**Comment by Methuselah96** [comment]
That is super weird. Maybe just a bug in TypeScript <=5.0? Does the error go away if you just remove the lines it's producing an error on?

**Comment by 0b5vr** [comment]
> That is super weird. Maybe just a bug in TypeScript <=5.0? Does the error go away if you just remove the lines it's producing an error on?

I'm sorry for the late reply. Yes, the error disappears once I comment out the lines. However, the issue persists on the end developer's code side 😖

**Comment by 0b5vr** [comment]
The `Type of property 'cache' circularly references itself in mapped type` error disappears once I bump the TypeScript version to 5.1.3 or above.
We might want to introduce some workarounds for 5.0 or below?

**Comment by Methuselah96** [comment]
Yeah, it's rather unfortunate. I'd be interested to know what kind of workarounds would make it work for 5.0 and below, and how it would impact the types for the user.

**Comment by 0b5vr** [comment]
> I'd be interested to know what kind of workarounds would make it work for 5.0 and below, and how it would impact the types for the user.

How do you think if we go ask for a help in [DefinitelyTyped issues](https://github.com/DefinitelyTyped/DefinitelyTyped/issues)...? low confidence.
They are probably experts of such type troubles.

**Comment by Methuselah96** [comment]
In my experience, those often don't get responded to. You might get a better response using [the TypeScript Community Discord server](https://discord.gg/typescript) (either the #definitely-typed channel or another channel). Or you could try asking about it on StackOverflow.

My schedule frees up in the next couple weeks so I should have some time to look into this soon regardless.

**Comment by 0b5vr** [comment]
ok thanks for the info! I might try either tomorrow

**Comment by 0b5vr** [comment]
I believe I made a minimal repro.
The reason is that `ContextNode` already has a member `.context` and `ShaderNodeObject` also gives it a method `.context`.

https://www.typescriptlang.org/play?ts=5.0.4#code/JYOwLgpgTgZghgYwgAgHIHsAmKDeBfAKANElkRQDF10NtkIAPSETAZzS1wOR+RmoBcyVmCigA5gG4ChBOhAi+g5AAoQnIbQgAaZJCZCRYkOICUyALwA+ZAGUAFnGxQtAeQBGAKwgIwAHioaThsLVXVsc2tVfGQ4djgQAE9TaWJwaHgkDmwAUQAbCABbCHB2HG5efnQhMESABwh0GCV0aUICRjr0KDA9epQHJ2g3Lx9-ABV6JhK2bIgQip4AMmRxxeQV8t5t5ABtAGkIRORQZABrI6a5-KKSsFYAXU1OG+LSg6OHqeZZtQ1V3QAOmBcCg4lYQlAMGgyAAgmDWJEbFCYQAldY7XgAflUwMBoPBQnh4KRyHRmMxQhAEAAbtBpNtCNsVlppEA

**Comment by 0b5vr** [comment]
I think I got a solution! Already pushed the commit to the branch

https://www.typescriptlang.org/play?ts=5.0.4#code/JYOwLgpgTgZghgYwgAgHIHsAmKDeBfAKANElkRQDF10NtkIAPSETAZzS1wOR+RmoBcyVmCigA5gG4ChBOhAi+g5AAoQnIbQgAaZJCZCRYkOICUyALwA+ZAGUAFnGxQtAeQBGAKwgIwAHioaThsLVXVsXX0wc2tVHG5efnQhKO0ZU2licGh4JA5sAFEAGwgAWwhwdnjeJWS9AE8ABwh0GFrpQgJGRvQoMAbmu0dnNy8ffwAVeiYKtnyIEISeADJkCaXkVeqa3gBtAGkIeuRQZABrI9b54rKKsFYAXSEpxmY5nGRdgAUTkGRD+pPX4waDIACqyEIO2hyAA-OCNjDkJpODdypUDkcHtM3uw1Bo1roAHQkuBQcSsISgEFQZAAQXJrBiNmpoIASoiYfCVCSiWSKUIGRTmcgOUiakIQBAAG7QaQ1KG8VZaaRAA

**Review by Methuselah96 — APPROVED** [review]
Nice work hunting that down!

**Pull request merged**
