### PR TITLE
feat: r147

### PR DESCRIPTION
**Pull request by 0b5vr**
This branch is to track r147 of three.js.

### What

three.js release: https://github.com/mrdoob/three.js/releases/tag/r147
three-ts-types issue: https://github.com/three-types/three-ts-types/issues/276

### Checklist

-   [x] Checked the target branch (current goes `master`, next goes `dev`)
-   [x] Added myself to contributors table
-   [x] Ready to be merged

### CODE REVIEW

**Comment by 0b5vr** [comment]
@joshuaellis done, review me. each commit belongs to a (set of) PR

**Review by joshuaellis — APPROVED** [review]

**Comment by 0b5vr** [comment]
@joshuaellis Thanks for the review! Should I merge this?

**Comment by joshuaellis** [comment]
In the future – yes, i've merged it now and i'll set up a PR over on DT.

**Comment by 0b5vr** [comment]
@joshuaellis thank you! It would be nice if you prepare a manual for creating a PR to the DefinitelyTyped repo (probably in CONTRIBUTING.md?).

**Pull request merged**
