### PR TITLE
fix: WebXR examples

### PR DESCRIPTION
**Pull request by capnmidnight**
### Why

There are a number of incorrect type definitions in the WebXR examples code. In particular:

 - `ARButton`s optional `sessionInit` constructor parameter is specified as `any`
 - `XRControllerModelFactory` is missing an `envMap` field
 - `OculusHandModel` and `OculusHandPointerModel` have a `motionController` field that is specified as `Object3D`, when a more specific type is avaiable
 - `XREstimatedLight`'s `lightProbe` field is specified as `unknown`
 - `XRHandModelFactory`'s `createHandModel` method's optional `profile` parameter includes `"oculus"` as a valid value, when that value has not been available for over a year.

### What

 - Change the `ARButton`s `sessionInit` constructor parameter to an extension of the XRSessionInit that provides for the option of specifying a `domOverlay` setting
 - Add an `envMap: Texture` field to `XRControllerModelFactory`
 - Change the `motionController` field in `OculusHandModel` and `OculusHandPointerModel` to be `XRHandMeshModel`
 - Change the `lightProbe` field in `XREstimatedLight`'s to be Three.js' `LightProbe` type.
 - Change the `profile` parameter in `XRHandModelFactory`'s `createHandModel` method's to accept `"mesh"` in place of `"oculus"`

### Checklist

-   [x] Checked the target branch (current goes `master`, next goes `dev`)
-   [x] Added myself to contributors table
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by capnmidnight** [comment]
So, I recently got a big change to the @types/webxr package to get them up to date. I've now modified my open PR here to include those types, as suggested in Issue #31.

**Comment by joshuaellis** [comment]
@Methuselah96 do you know why the CI is unhappy with this PR?

**Comment by Methuselah96** [comment]
@joshuaellis It's due to the change in `package.json`. `yarn install` needs to be run to update the lock file.

**Comment by capnmidnight** [comment]
I had committed the modified yarn.lock, but the CI complained about it. So I reverted it and the CI complained again. I just ran `yarn install` again and the changes this time are much less than last time, so I have committed it again.

**Review by joshuaellis — APPROVED** [review]

**Pull request merged**
