### PR TITLE
fix: complete optional parameters.

### PR DESCRIPTION
**Pull request by khum08**

### CODE REVIEW

**Comment by joshuaellis** [comment]
Thanks for the contribution @khum08, can you provide a source of why this change was made, please?

**Comment by khum08** [comment]
> Thanks for the contribution @khum08, can you provide a source of why this change was made, please?

I just found parameters in those funtion are different to js source file. you means developer don't need to pass 'update' param when they call those function directly?

**Comment by khum08** [comment]
here is js source code.
image
image

**Review by joshuaellis — APPROVED** [review]
Looks good to me, thanks for the contribution.

**Comment by joshuaellis** [comment]
@all-contributors please add @khum08  for code

**Pull request merged**
