### PR TITLE
DataTextureLoader.load() should return DataTexture

### PR DESCRIPTION
**Pull request by marquizzo**
### Why

Looking [at the source code](https://github.com/mrdoob/three.js/blob/350f0a021943d6fa1d039a7c14c303653daa463f/src/loaders/DataTextureLoader.js#L22-L103), and also [the documentation](https://threejs.org/docs/index.html#api/en/loaders/DataTextureLoader.load), `DataTextureLoader.load()` should return a `DataTexture` instead of `void`.

### What

I simply replaced `:void` with `:DataTexture` in the return type for the `.load()` method.

### Checklist
-   [x] Ready to be merged

### CODE REVIEW

**Comment by joshuaellis** [comment]
Hi @marquizzo would you mind creating a test for this? We normally just copy the relevant html example from the `three` repo.

**Review by joshuaellis — APPROVED** [review]
Reviewing this file, it doesn't appear that there's a suffiecent `html` example to take from the `three` repo as it's part of most other loaders e.g. `RGBELoader`. So i'm going to approve this merger based on that.

**Comment by joshuaellis** [comment]
@all-contributors please add @marquizzo  for code

**Comment by marquizzo** [comment]
Thanks @joshuaellis ! I meant to build the test, but work has been really busy. Glad it could be merged without it!

**Pull request merged**
