### PR TITLE
Update TransformControls.d.ts

### PR DESCRIPTION
**Pull request by puxiao**
### What

Add some type options.

### CODE REVIEW

**Comment by joshuaellis** [comment]
Can you write a test for this please?

**Comment by puxiao** [comment]
> Can you write a test for this please?

These option values are all present in `TransformControls.js`. 
I think it can avoid handwriting errors after adding it.

I don't quite understand what you mean by letting me add tests.
I don't know how to write test cases.
emm... automated test ?

**Comment by joshuaellis** [comment]
Check out the test file, they're typically the html example from the three repo. Its just for type safety.

**Comment by puxiao** [comment]
> Check out the test file, they're typically the html example from the three repo. Its just for type safety.

I did not find `examples/jsm` in `three-ts-types/types/three/test/`.
I am really not sure what I should add.

In my development, I have not written test cases.
em.......
Can you give me some guidance?

**Comment by joshuaellis** [comment]
I think i've written a test for TransformControls, for future reference.

**Review by joshuaellis — APPROVED** [review]

**Pull request merged**
