### PR TITLE
Add createInterpolant to KeyframeTrack

### PR DESCRIPTION
**Pull request by marwie**
### Why

Keyframetracks were missing ``createInterpolant`` https://threejs.org/docs/#api/en/animation/KeyframeTrack.createInterpolant

### What

https://threejs.org/docs/#api/en/animation/KeyframeTrack.createInterpolant

### Checklist

-   [x] Checked the target branch (current goes `master`, next goes `dev`)
-   [x] Added myself to contributors table
-   [x] Ready to be merged

### CODE REVIEW

**Review by joshuaellis — APPROVED** [review]

**Review by 0b5vr — CHANGES_REQUESTED** [review]
You forgot pushing `.all-contributorsrc` ?

**Comment by marwie** [comment]
Fixed !

**Comment by 0b5vr** [comment]
what a fast response, thanks

**Review by 0b5vr — APPROVED** [review]

**Comment by 0b5vr** [comment]
Aaand it's conflicted

**Comment by marwie** [comment]
Ah oh no, one sec

**Comment by marwie** [comment]
Rebased on master and added my changes to readme + the contributors file again

**Comment by 0b5vr** [comment]
Thanks!

**Pull request merged**
