### PR TITLE
`Object3D`: class instances

### PR DESCRIPTION
**Pull request by Hoodgail**

### CODE REVIEW

**Comment by joshuaellis** [comment]
CI failing.

**Comment by Hoodgail** [comment]
> CI failing.

image
No idea why

**Comment by joshuaellis** [comment]
> > CI failing.
> 
> image No idea why

I would look at the test files that are failing and try to address from there.

**Comment by 0b5vr** [comment]
What is the motivation for this change? I thought the use of `this` here is helpful on subclasses.

**Comment by Hoodgail** [comment]
> What is the motivation for this change? I thought the use of `this` here is helpful on subclasses.
@0b5vr 
I made some more reviewing and i think you're right, i don't remember the error i was getting with `:this`

But now i wonder why the others don't do the same like `BufferGeometry`

image
image
image

**Comment by 0b5vr** [comment]
mmm yes, I think `BoxGeometry.clone` should return `BoxGeometry`.

**Pull request closed without merging**
